### PR TITLE
Allow for custom admin url

### LINKED ISSUE #17: Custom admin url
Is there a way to pass in the value for base_admin if you use a custom admin url?

Thanks,

### PR DESCRIPTION
**Pull request by bee-keeper**
Fix #17

### CODE REVIEW

**Comment by yakky** [comment]
Assigning to mysef for review

**Comment by yakky** [comment]
@bee-keeper LGTM. Could you port the same change to ``static/djangocms_text_ckeditor/ckeditor/plugins/filerimage/plugin.js`` and ``static/djangocms_text_ckeditor/ckeditor/plugins/filerimage/dialogs/filerImageDialog.js``: both versions must be kept in sync

**Comment by bee-keeper** [comment]
Good point, there you go.  

I think at some point it would be best to try and reduce the ajax calls and just have 1 to do to setup and config.  But for now this works.

**Comment by yakky** [comment]
@bee-keeper awesome! I'm open to further improvements for this package. I'm going to release b13 soon (I really go forward a releease a stable one!)

**Pull request merged**
